from .Clientes import Clientes as ClientesResource
from .Clientes import Cliente as ClienteResource
from .Usuarios import Usuario as UsuarioResource
from .Usuarios import Usuarios as UsuariosResource
from .Productos import Producto as ProductoResource
from .Productos import Productos as ProductosResource
from .ProductosCompras import ProductosCompras as ProductosComprasResource
from .ProductosCompras import ProductoCompra as ProductoCompraResource
from .Compras import Compras as ComprasResource
from .Compras import Compra as CompraResource
